import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Profile card</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon-32x32.png" />
      </Head>
      <div className={styles.bgtop}>
        <img 
          src="/bg-pattern-top.svg"
          alt="top left"
        />
      </div>
      <div className={styles.cardcontainer}>
        <img 
          src="/bg-pattern-card.svg"
          alt="card bg"
          className={styles.cardbg}
        />
        <div className={styles.profilephoto}>
          <div className={styles.photo}>
            <img 
              src="/image-victor.jpg"
              alt="profile photo"
            />
          </div>
        </div>
        <div className={styles.name}>
          <h4>
            Victor Crest 
            <span>&nbsp;</span>
            <span className={styles.age}>
              26
            </span>
          </h4>
        </div>
        <div className={styles.location}>
          <h4>London</h4>
        </div>
        <div className={styles.horizontalline}>
        </div>
        <div className={styles.numbers}>
          <div className={styles.category}>
            80k
            <div className={styles.categoryname}>
              Followers
            </div>
          </div>
          <div className={styles.category}> 
            803k
            <div className={styles.categoryname}>
              Likes
            </div>
          </div>
          <div className={styles.category}> 
            1.4k
            <div className={styles.categoryname}>
              Photos
            </div>
          </div>
        </div>
      </div>
      <div className={styles.bgbottom}>
        <img 
          src="/bg-pattern-bottom.svg"
          alt="bottom right"
        />
      </div>
    </div>
  )
}
